In [149]:
# Importação de bibliotecas necessárias
import pandas as pd
import nbformat as nbf
import ipykernel
import plotly.express as px
import openpyxl

In [150]:
#Importar e visualizar a base de dados
tabela = pd.read_csv("Base de dados.csv")
display(tabela)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [151]:
# Análise de dados faltantes
print(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB
None

In [152]:
# Remover colunas desnecessárias
tabela = tabela.drop(columns=["EmployeeNumber", "EmployeeCount", "Over18", "StandardHours"])
display(tabela)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,3,3,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,3,1,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,4,2,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,3,4,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,3,1,0,6,3,4,4,3,1,2

In [153]:
# Análise e visualização dos dados iniciais
lista = tabela["Attrition"].value_counts(normalize=True)
print(lista)

Attrition
No     0.838776
Yes    0.161224
Name: proportion, dtype: float64

In [154]:
#Análise detalhada (Padrões de demissão da empresa)
for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color="Attrition", barmode="group", barnorm="percent")
    grafico.show()

In [155]:
#Gasto anual com os funcionários
gasto_total = tabela["MonthlyIncome"].sum() * 12
print("O gasto anual com os funcionários é: R$", gasto_total) 
#Gasto anual de reposição de funcionários devido à demissões
gasto_anual = tabela[tabela["Attrition"] == "Yes"]["MonthlyIncome"].sum() * 12 * 1.5
print("O gasto anual de reposição de funcionários é: R$", gasto_anual)

O gasto anual com os funcionários é: R$ 114711708
O gasto anual de reposição de funcionários é: R$ 20421738.0

In [ ]:
#Pessoas mais jovens tendem a sair mais da empresa
    #Solução: Programas de mentoria e desenvolvimento de carreira
#Funcionários com renda mensal abaixo de 2000 tendem a sair mais da empresa
    #Solução: Revisão de pacotes salariais e benefícios
#Nova porcentagem de demissão
 = (tabela["MonthlyIncome"] < 3000) & (tabela["Age"] < 30)
tabela.loccondicao[condicao, "Attrition"] = "No"
display(tabela["Attrition"].value_counts(normalize=True))
#Economia anual com a redução de demissões
novo_gasto_anual = tabela[tabela["Attrition"] == "Yes"]["MonthlyIncome"].sum() * 12 * 1.5
economia = gasto_anual - novo_gasto_anual
print("A economia anual com a redução de demissões é: R$", economia)
dados_economia = {
    "Categoria": ["Gasto Original", "Novo Gasto", "Economia"],
    "Valor": [gasto_anual, novo_gasto_anual, economia]
}

tabela_economia = pd.DataFrame(dados_economia)
grafico = px.histogram(tabela_economia, x=["Gasto Original", "Novo Gasto", "Economia"], y="Valor", barmode="group", color="Categoria")
grafico.show()

Attrition
No     0.882313
Yes    0.117687
Name: proportion, dtype: float64

A economia anual com a redução de demissões é: R$ 2585124.0